[tool.poetry]
name = "pyettj"
version = "0.2.4"
description = "Coletar dados de curvas de juros (ettj)."
authors = ["Rafael Rodrigues <rafael.rafarod@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"
requests = "^2.25.1"
beautifulsoup4 = "^4.9.3"
matplotlib = "^3.4.2"
lxml = "^4.6.3"
bizdays = "^0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
coverage = "^5.5"
mypy = "^0.812"
pre-commit = "^2.13.0"
codecov = "^2.1.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
